### ISSUE TITLE
Can you upload environment files and scripts? 

### ISSUE THREAD

**Issue by junghan0611** [Pfzuo/Path-Hashing#1]
I have prepared the Gem5 with NVMain environment.
But, I don't have any idea how to make the experimental configurations you did. 
(Table 1 in your paper) 

If you could, upload some environment files and give some readme on the GitHub.
- Gem5 run scripts
- NVMAIN PCM Config File (16GB, Read latency 75, Write Latency 150ns) 

Thanks.

**Comment by Pfzuo** [comment]
You can use the PCM_ISSCC_2012_4GB.config file in NVMmain, and revise the number of banks to 16 to achive a 16GB capicity, and revise the timing pameters as needed.
